var express = require('express')
const passport = require('passport')
var router = express.Router()

const userRoutes = require('./users')
const rolRoutes = require('./rols')
const usuariRoutes = require('./usuaris')
const serveiRoutes = require('./serveis')
const taskRoutes = require('./tasks')
const tipusactuacionsRoutes = require('./tipusactuacions')
const seguimentRoutes = require('./seguiments')
const dimensioRoutes = require('./dimensions')
const actuacioRoutes = require('./actuacions')
const paiRoutes = require('./pais')
const operationRoutes = require('./operations')
const signupRoutes = require('./signup')
const loginRoutes = require('./login')

router
  .use("/users",  passport.authenticate('jwt', { session: false }), userRoutes)
  .use("/rols", passport.authenticate('jwt', { session: false }), rolRoutes)
  .use("/usuaris", passport.authenticate('jwt', { session: false }), usuariRoutes)
  .use("/serveis", passport.authenticate('jwt', { session: false }), serveiRoutes)
  .use("/tasks", passport.authenticate('jwt', { session: false }), taskRoutes)
  .use("/tipusactuacions", passport.authenticate('jwt', { session: false }), tipusactuacionsRoutes)
  .use("/seguiments", passport.authenticate('jwt', { session: false }), seguimentRoutes)
  .use("/dimensions", passport.authenticate('jwt', { session: false }), dimensioRoutes)
  .use("/actuacions", passport.authenticate('jwt', { session: false }), actuacioRoutes)
  .use("/pais", passport.authenticate('jwt', { session: false }), paiRoutes)
  .use("/operations", passport.authenticate('jwt', { session: false }), operationRoutes)
  .use('/', passport.authenticate('jwt', { session: false }), signupRoutes)
  .use('/', passport.authenticate('jwt', { session: false }), loginRoutes)

module.exports = router
